name: citk_connect # IMPORTANT: Ensure this matches your import statements
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0' # Fixes "experiment_not_enabled" errors

dependencies:
  flutter:
    sdk: flutter
  # Fixes "uri_does_not_exist" for packages
  flutter_riverpod: ^2.6.0
  hooks_riverpod: ^2.6.0
  flutter_hooks: ^0.20.0
  riverpod_annotation: ^2.6.0
  cloud_firestore: ^5.0.0 # For the Database
  go_router: ^17.0.1
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_remote_config: ^5.1.3
  firebase_analytics: ^11.3.3
  # ... your other dependencies ...
  flutter_animate: ^4.5.0  # Fixes the ".ms" and "animate" errors
  google_sign_in: ^6.2.1   # Fixes the GoogleSignIn error
  google_fonts: ^6.1.0     # For that clean "Google Product" look
  font_awesome_flutter: ^10.6.0 # For the Google Logo icon  
  #Web
  url_launcher: ^6.3.2
  firebase_ai: ^2.3.0
  google_maps_flutter: ^2.14.0
  shared_preferences: ^2.5.4
  geolocator: ^14.0.2
  share_plus: ^12.0.1
  flutter_tts: ^4.2.3
  firebase_storage: ^12.4.10
  image_picker: ^1.2.1
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.3.1
  image_cropper: ^8.0.2
  firebase_messaging: ^15.2.10

  # Add other existing dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  # Required for generating .g.dart files
  build_runner: ^2.4.0
  riverpod_generator: ^2.6.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # <--- Point to your image file
  min_sdk_android: 21 # optional


flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Fixes "asset_directory_does_not_exist"
    - assets/data/citk_data.json

    # Fonts 
fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic