name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 2. Install Dependencies
      - run: flutter pub get

      # 3. Build Web Version (Release Mode)
      - run: flutter build web --release

      # 4. Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # Make sure this matches the secret name in your GitHub Settings!
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CITK_CONNECT_CORE }}'
          projectId: citk-connect-project